language: r
sudo: false
cache: packages
warnings_are_errors: false

latex: true
r_build_args: '--no-build-vignettes'
r_check_args: '--ignore-vignettes --no-examples'

r_github_packages:
  - jimhester/covr

env:
  matrix:
    - CXX_OLEVEL=2 CXX=clang++

before_install:
  - sudo apt-get -y install libv8-dev
  - mkdir -p ~/.R/
  - echo "CXX = `R CMD config CXX`" >> ~/.R/Makevars
  - echo "CXXFLAGS = `R CMD config CXXFLAGS` -pedantic -g0" >> ~/.R/Makevars
  - export CLANG_EXTRA_ARG=""
  - if [[ $CXX = "clang++" ]] ;  then export CLANG_EXTRA_ARG=" -Qunused-arguments -fcolor-diagnostics " ; fi
  - sed -i.bak "s/ g++/ ${CXX}${CLANG_EXTRA_ARG}/" ~/.R/Makevars
  - sed -i.bak "s/O[0-3]/O$CXX_OLEVEL/" ~/.R/Makevars
  - echo "options(repos = c(CRAN = 'https://packagemanager.rstudio.com/all/__linux__/xenial/latest'))" >> ~/.Rprofile.site
  - echo "options(HTTPUserAgent = paste0('R/', getRversion(), ' R (',
       paste(getRversion(), R.version['platform'], R.version['arch'], R.version['os']),
       ')'))" >> ~/.Rprofile.site

script:
  - travis_wait 120 R CMD build . --no-build-vignettes
  - travis_wait 120 R CMD check projpred*tar.gz --ignore-vignettes --no-examples

after_success:
- travis_wait 120 Rscript -e 'covr::codecov()'
